[workspace]
resolver = "2"
members = [
    "client",
    "bookapp",
    "bookapp-dal",
    "tests",
    "preaggregated-metrics",
]

[workspace.dependencies]
axum = { version = "0.8.9" }
tower = "0.5.3"
reqwest = "0.13.4"
opentelemetry = "0.32.0"
tracing = { version = "0.1.44" }
tracing-opentelemetry = { version = "0.33.0" }
