CREATE SCHEMA IF NOT EXISTS error_injection;

CREATE TABLE IF NOT EXISTS error_injection.config (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_pattern TEXT NOT NULL,
    http_method TEXT NOT NULL,
    error_rate DOUBLE PRECISION NOT NULL CHECK (error_rate >= 0 AND error_rate <= 1),
    error_code INTEGER NOT NULL,
    error_message TEXT,
    latency_ms INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS error_injection_config_pattern_method_idx
    ON error_injection.config (endpoint_pattern, http_method);

DO $$
BEGIN
    IF to_regclass('public.error_injection_config') IS NOT NULL THEN
        INSERT INTO error_injection.config (
            id,
            endpoint_pattern,
            http_method,
            error_rate,
            error_code,
            error_message,
            latency_ms
        )
        SELECT
            id,
            endpoint_pattern,
            http_method,
            error_rate,
            error_code,
            error_message,
            latency_ms
        FROM public.error_injection_config
        ON CONFLICT (id) DO NOTHING;

        DROP TABLE public.error_injection_config;
    END IF;
END $$;

SELECT setval(
    'error_injection.config_id_seq',
    GREATEST(1, COALESCE((SELECT MAX(id) FROM error_injection.config), 1))
);
